changelog:
  categories:
    - title: 新機能
      labels:
        - enhancement
    - title: バグ修正
      labels:
        - bug
        - fixes
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
