name: Artifacts4
on: push
jobs:
  downloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          dbid=$(gh run list --workflow artifacts4.yml --json databaseId --jq .'[1].databaseId')
          echo $dbid
          gh run download $dbid --name uploaded --dir .
          cat date.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
  upload:
    runs-on: ubuntu-latest
    needs: downloads
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
