name: Conftest
on: workflow_dispatch

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" openpolicyagent/conftest test --policy policy/ .github/workflows
