name: Job summaries
on: push

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF >> "${GITHUB_STEP_SUMMARY}"
          ## Example Title :rocket:
          - first line
          - second line
          EOF
