name: Log group
on: push

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SuperSecretValue
    steps:
      - run: |
          echo "::add-mask::${PASSWORD}"
          echo "${PASSWORD}"
