name: Modified cross repo
on: workflow_dispatch
env:
  TARGET_REPO: auto_click
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: create
        run: |
          chomod +x .github/scripts/token.sh
          .github/scripts/token.sh
        env:
          APP_ID: ${{secrets.APP_ID}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      - uses: actions/checkout@v4
        with:
          repository: ${{github.repository_owner}}/${{env.TARGET_REPO}}
          path: ${{env.TARGET_REPO}}
          token: ${{steps.create.outputs.token}}
      - run: cat "${TARGET_REPO}/README.md"
